src/main/java/net/therap/virtualexam/domain/Questionnaire.java
package net.therap.virtualexam.domain;

import org.json.JSONArray;
import org.json.JSONObject;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.stream.IntStream;

import static javax.persistence.CascadeType.ALL;

/**
 * @author tanmoy.das
 * @since 6/1/20
 */
@NamedQueries({
        @NamedQuery(name = "Questionnaire.findAll",
                query = "FROM Questionnaire questionnaire " +
                        "WHERE questionnaire.status != :status")
})
@Entity
@Table(name = "questionnaire")
public class Questionnaire extends Persistence {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @NotEmpty(message = "{error.emptyQuestionnaireLabel}")
    private String label;

    @ManyToOne(optional = false)
    @JoinColumn(name = "subject_id")
    private Subject subject;

    private String chaptersJson;

    @ManyToMany(cascade = ALL)
    @JoinTable(
            name = "questionnaire_question",
            joinColumns = {@JoinColumn(name = "questionnaire_id")},
            inverseJoinColumns = {@JoinColumn(name = "question_id")}
    )
    private List<Question> questions;

    private String questionOrderJson;

    @OneToMany(mappedBy = "questionnaire", cascade = ALL)
    private List<QuestionnaireAssignment> questionnaireAssignments;

    @ManyToOne(optional = false)
    @JoinColumn(name = "created_by_id")
    private User createdBy;

    @Temporal(TemporalType.TIMESTAMP)
    private Date deleted;

    @ManyToOne
    @JoinColumn(name = "deleted_by_id")
    private User deletedBy;

    @Enumerated(EnumType.STRING)
    private Status status;

    public boolean isNew() {
        return getId() == 0;
    }

    public List<String> getChapterLabels() {
        JSONArray chapterList = new JSONArray(chaptersJson);
        List<String> chapterNames = new ArrayList<>();

        IntStream.range(0, chapterList.length())
                .forEach(index -> {
                    JSONObject chapterJson = chapterList.getJSONObject(index);
                    chapterNames.add(chapterJson.getString("label"));
                });

        return chapterNames;
    }

    public List<Long> getChapterIds() {
        JSONArray chapterList = new JSONArray(chaptersJson);
        List<Long> chapterIds = new ArrayList<>();

        IntStream.range(0, chapterList.length())
                .forEach(index -> {
                    JSONObject chapterJson = chapterList.getJSONObject(index);
                    chapterIds.add(chapterJson.getLong("id"));
                });

        return chapterIds;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Date getDeleted() {
        return deleted;
    }

    public void setDeleted(Date deleted) {
        this.deleted = deleted;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public String getChaptersJson() {
        return chaptersJson;
    }

    public void setChaptersJson(String chapters) {
        this.chaptersJson = chapters;
    }

    public String getQuestionOrderJson() {
        return questionOrderJson;
    }

    public void setQuestionOrderJson(String questionOrder) {
        this.questionOrderJson = questionOrder;
    }

    public List<Question> getQuestions() {
        return questions;
    }

    public void setQuestions(List<Question> questions) {
        this.questions = questions;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public User getDeletedBy() {
        return deletedBy;
    }

    public void setDeletedBy(User deletedBy) {
        this.deletedBy = deletedBy;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public List<QuestionnaireAssignment> getQuestionnaireAssignments() {
        return questionnaireAssignments;
    }

    public void setQuestionnaireAssignments(List<QuestionnaireAssignment> questionnaireAssignments) {
        this.questionnaireAssignments = questionnaireAssignments;
    }
}

src/main/java/net/therap/virtualexam/domain/QuestionnaireAssignment.java
package net.therap.virtualexam.domain;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * @author tanmoy.das
 * @since 6/1/20
 */
@NamedQueries({
        @NamedQuery(name = "QuestionnaireAssignment.findAll",
                query = "FROM QuestionnaireAssignment questionnaireAssignment " +
                        "WHERE questionnaireAssignment.status != :status")
})
@Entity
@Table(name = "questionnaire_assignment")
public class QuestionnaireAssignment extends Persistence {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @NotNull
    @ManyToOne(optional = false)
    @JoinColumn(name = "assignee_id")
    private User assignee;

    @NotNull
    @ManyToOne(optional = false)
    @JoinColumn(name = "questionnaire_id")
    private Questionnaire questionnaire;

    @ManyToOne(optional = false)
    @JoinColumn(name = "created_by_id")
    private User createdBy;

    @Temporal(TemporalType.TIMESTAMP)
    private Date deleted;

    @ManyToOne
    @JoinColumn(name = "deleted_by_id")
    private User deletedBy;

    @Enumerated(EnumType.STRING)
    private Status status;

    public boolean isNew() {
        return getId() == 0;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public User getAssignee() {
        return assignee;
    }

    public void setAssignee(User assignee) {
        this.assignee = assignee;
    }

    public Questionnaire getQuestionnaire() {
        return questionnaire;
    }

    public void setQuestionnaire(Questionnaire questionnaire) {
        this.questionnaire = questionnaire;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public Date getDeleted() {
        return deleted;
    }

    public void setDeleted(Date deleted) {
        this.deleted = deleted;
    }

    public User getDeletedBy() {
        return deletedBy;
    }

    public void setDeletedBy(User deletedBy) {
        this.deletedBy = deletedBy;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }
}

src/main/java/net/therap/virtualexam/web/controller/DashboardController.java
package net.therap.virtualexam.web.controller;

import net.therap.virtualexam.domain.User;
import net.therap.virtualexam.exception.WebAccessException;
import net.therap.virtualexam.service.SubjectService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpSession;

import static net.therap.virtualexam.domain.Role.STUDENT;
import static net.therap.virtualexam.domain.Role.TEACHER;
import static net.therap.virtualexam.util.Constants.CURRENT_USER_LABEL;
import static net.therap.virtualexam.util.Constants.SUBJECTS_LABEL;

/**
 * @author tanmoy.das
 * @since 4/8/20
 */
@Controller
public class DashboardController {

    private static final Logger logger = LoggerFactory.getLogger(DashboardController.class);

    private static final String DASHBOARD_PAGE = "dashboard";
    private static final String STUDENT_HOMEPAGE = "home";

    @Autowired
    private SubjectService subjectService;

    @RequestMapping(value = "dashboard", method = RequestMethod.GET)
    public String showDashboardPage(ModelMap model, HttpSession session) {
        User currentUser = (User) session.getAttribute(CURRENT_USER_LABEL);
        checkTeacherAccess(currentUser);

        return DASHBOARD_PAGE;
    }

    @RequestMapping(value = "home", method = RequestMethod.GET)
    public String showStudentHomePage(ModelMap model, HttpSession session) {
        User currentUser = (User) session.getAttribute(CURRENT_USER_LABEL);
        checkStudentAccess(currentUser);

        //TODO:IMPLEMENT LOGIC
        return STUDENT_HOMEPAGE;
    }

    @ModelAttribute
    public void addAttributes(ModelMap model) {
        model.put(SUBJECTS_LABEL, subjectService.findAll());
    }

    private void checkTeacherAccess(User currentUser) {
        if (currentUser.getRole() == STUDENT) {
            throw new WebAccessException();
        }
    }

    private void checkStudentAccess(User currentUser) {
        if (currentUser.getRole() == TEACHER) {
            throw new WebAccessException();
        }
    }
}

src/main/java/net/therap/virtualexam/web/controller/ErrorController.java
package net.therap.virtualexam.web.controller;

import net.therap.virtualexam.service.SubjectService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import static net.therap.virtualexam.util.Constants.SUBJECTS_LABEL;

/**
 * @author tanmoy.das
 * @since 4/8/20
 */
@Controller
@RequestMapping("error")
public class ErrorController {

    private static final Logger logger = LoggerFactory.getLogger(ErrorController.class);
    private static final String ERROR_PAGE = "error";

    @Autowired
    private SubjectService subjectService;

    @RequestMapping(value = {"", "/"}, method = RequestMethod.GET)
    public String showAddQuestionnairePage() {
        logger.error("Unexpected Error Occurred");

        return ERROR_PAGE;
    }

    @RequestMapping(value = {"", "/"}, params = "errorCode", method = RequestMethod.GET)
    public String showAddQuestionnairePageWithError(@RequestParam("errorCode") String errorCode,
                                                    ModelMap model) {

        logger.error("Unexpected Error Occurred");
        model.put("errorCode", errorCode);

        return ERROR_PAGE;
    }


    @ModelAttribute
    public void addAttributes(ModelMap model) {
        model.put(SUBJECTS_LABEL, subjectService.findAll());
    }
}

src/main/java/net/therap/virtualexam/web/controller/QuestionnaireAssignmentController.java
package net.therap.virtualexam.web.controller;

import net.therap.virtualexam.command.QuestionnaireAssignmentCommand;
import net.therap.virtualexam.domain.Questionnaire;
import net.therap.virtualexam.domain.QuestionnaireAssignment;
import net.therap.virtualexam.domain.User;
import net.therap.virtualexam.exception.WebAccessException;
import net.therap.virtualexam.service.QuestionnaireAssignmentService;
import net.therap.virtualexam.service.QuestionnaireService;
import net.therap.virtualexam.service.SubjectService;
import net.therap.virtualexam.service.UserService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.support.SessionStatus;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import java.util.List;

import static net.therap.virtualexam.domain.Role.STUDENT;
import static net.therap.virtualexam.helper.UrlHelper.redirectTo;
import static net.therap.virtualexam.util.Constants.CURRENT_USER_LABEL;
import static net.therap.virtualexam.util.Constants.SUBJECTS_LABEL;

/**
 * @author tanmoy.das
 * @since 4/8/20
 */
@Controller
@SessionAttributes({"questionnaireAssignmentCommand", "currentQuestionnaire", "students"})
@RequestMapping("questionnaireAssignment")
public class QuestionnaireAssignmentController {

    private static final Logger logger = LoggerFactory.getLogger(QuestionnaireAssignmentController.class);

    private static final String QUESTIONNAIRE_ASSIGNMENT_PAGE = "questionnaireAssignment";
    private static final String CURRENT_QUESTIONNAIRE_LABEL = "currentQuestionnaire";
    private static final String QUESTIONNAIRE_ASSIGNMENT_COMMAND_LABEL = "questionnaireAssignmentCommand";
    private static final String STUDENTS_LABEL = "students";

    @Autowired
    private QuestionnaireAssignmentService questionnaireAssignmentService;

    @Autowired
    private QuestionnaireService questionnaireService;

    @Autowired
    private UserService userService;

    @Autowired
    private SubjectService subjectService;

    @RequestMapping(value = "index", method = RequestMethod.GET)
    public String showIndexPage(@RequestParam("questionnaireId") long questionnaireId,
                                ModelMap model,
                                HttpSession session) {

        checkAccess(session);

        Questionnaire questionnaire = questionnaireService.find(questionnaireId)
                .orElseThrow(IllegalArgumentException::new);
        model.put(CURRENT_QUESTIONNAIRE_LABEL, questionnaire);

        User currentUser = (User) session.getAttribute(CURRENT_USER_LABEL);

        QuestionnaireAssignmentCommand questionnaireAssignmentCommand = new QuestionnaireAssignmentCommand();
        questionnaireAssignmentCommand.getQuestionnaireAssignment().setQuestionnaire(questionnaire);
        questionnaireAssignmentCommand.getQuestionnaireAssignment().setCreatedBy(currentUser);
        model.put(QUESTIONNAIRE_ASSIGNMENT_COMMAND_LABEL, questionnaireAssignmentCommand);

        List<User> students = userService.findAllStudents();
        model.put(STUDENTS_LABEL, students);

        return QUESTIONNAIRE_ASSIGNMENT_PAGE;
    }

//    @RequestMapping(value = "addQuestionnaireAssignment", method = RequestMethod.GET)
//    public String showAddQuestionnaireAssignmentPage(ModelMap model, HttpSession session) {
//        User currentUser = (User) session.getAttribute(CURRENT_USER_LABEL);
//        checkAccess(session);
//
//        QuestionnaireAssignmentCommand questionnaireAssignmentCommand = new QuestionnaireAssignmentCommand();
//        questionnaireAssignmentCommand.getQuestionnaireAssignment().setCreatedBy(currentUser);
//
//        model.put(SUBJECT_COMMAND_LABEL, questionnaireAssignmentCommand);
//        return ADD_SUBJECT_PAGE;
//    }

    @RequestMapping(value = "submit", method = RequestMethod.POST)
    public String addQuestionnaireAssignment(@Valid
                                             @ModelAttribute(QUESTIONNAIRE_ASSIGNMENT_COMMAND_LABEL)
                                                     QuestionnaireAssignmentCommand questionnaireAssignmentCommand,
                                             BindingResult bindingResult,
                                             ModelMap model,
                                             HttpSession session,
                                             SessionStatus sessionStatus) {

        checkAccess(session);

        if (bindingResult.hasErrors()) {
            return QUESTIONNAIRE_ASSIGNMENT_PAGE;
        }

        QuestionnaireAssignment questionnaireAssignment = questionnaireAssignmentCommand.getQuestionnaireAssignment();
        Questionnaire questionnaire = questionnaireAssignment.getQuestionnaire();

        questionnaireAssignmentService.approve(questionnaireAssignment);
        questionnaire.getQuestionnaireAssignments().add(questionnaireAssignment);
        questionnaireService.saveOrUpdate(questionnaire);

        sessionStatus.setComplete();

        String questionnaireAssignmentUrl = "/questionnaireAssignment/index?questionnaireId=" +
                questionnaireAssignment.getQuestionnaire().getId();
        return redirectTo(questionnaireAssignmentUrl);
    }

    @ModelAttribute
    public void addAttributes(ModelMap model) {
        model.put(SUBJECTS_LABEL, subjectService.findAll());
    }

    private void checkAccess(HttpSession session) {
        User currentUser = (User) session.getAttribute(CURRENT_USER_LABEL);

        if (currentUser.getRole() == STUDENT) {
            throw new WebAccessException();
        }
    }
}

src/main/webapp/WEB-INF/views/addAnswerOption.jsp
<%--
  @author tanmoy.das
  @since 5/2/20
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<spring:message code="label.app.description"/>">
    <meta name="author" content="<spring:message code="label.author.name"/>">

    <title><spring:message code="label.dashboard"/></title>

    <c:url var="dashboardCssUrl" value="/css/dashboard.css"/>
    <link rel="stylesheet" type="text/css" href="${dashboardCssUrl}">
</head>

<body>
<div class="wrapper">
    <!-- Sidebar  -->
    <%@ include file="/WEB-INF/includes/sections/leftSideBar.jsp" %>

    <!-- Page Content  -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fas fa-align-left"></i>
                    <span></span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-align-justify"></i>
                </button>

                <h2 class="mx-3">
                    <spring:message code="label.addAnswerOption"/>
                </h2>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                </div>

            </div>
        </nav>

        <div class="tab-content">
            <c:url var="addAnswerOptionUrl" value="/answerOption/submit"/>
            <%--@elvariable id="answerOptionCommand" type="net.therap.virtualexam.command.AnswerOptionCommand"--%>
            <form:form modelAttribute="answerOptionCommand" method="post" action="${addAnswerOptionUrl}">
                <c:set var="answerOption" value="${answerOptionCommand.answerOption}"/>

                <div class="form-group">
                    <h5>
                        <span class="text-muted">
                            <spring:message code="label.questionCode"/>:
                        </span>
                        <span> <c:out value="${answerOption.question.code}"/></span>
                    </h5>
                    <h5>
                        <span class="text-muted">
                            <spring:message code="label.questionTitle"/>:
                        </span>
                        <span> <c:out value="${answerOption.question.title}"/></span>
                    </h5>
                    <h5>
                        <span class="text-muted">
                            <spring:message code="label.questionHint"/>:
                        </span>
                        <span> <c:out value="${answerOption.question.hint}"/></span>
                    </h5>

                </div>

                <div class="form-group">
                    <form:label path="answerOption.label">
                        <spring:message code="label.answerOptionLabel"/>
                    </form:label>
                    <form:input path="answerOption.label" cssClass="form-control"
                                aria-describedby="emailHelp" placeholder="Answer Option Text"/>
                    <small id="questionCodeHint" class="form-text text-muted">
                        <spring:message code="enterAnswerOptionText"/>
                    </small>
                </div>

                <div class="form-group">
                    <div class="form-check">
                        <form:checkbox path="answerOption.correct" cssClass="form-check-input"/>
                        <form:label path="answerOption.correct" cssClass="form-check-label">
                            <spring:message code="label.correctOption"/>
                        </form:label>
                    </div>
                </div>

                <%--                <c:url var="homepageUrl" value="/"/>--%>
                <%--                <a href="${homepageUrl}" type="submit" class="btn btn-primary">Save</a>--%>

                <form:button type="submit" class="btn btn-primary" name="_action_save">
                    Save
                </form:button>

                <form:button type="submit" class="btn btn-secondary" name="_action_save_and_add">
                    Save and Add Another Option
                </form:button>

            </form:form>
        </div>
    </div>
</div>


<!-- jQuery Custom Scroller CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#sidebar").mCustomScrollbar({
            theme: "minimal"
        });

        $('#sidebarCollapse').on('click', function () {
            $('#sidebar, #content').toggleClass('active');
            $('.collapse.in').toggleClass('in');
            $('a[aria-expanded=true]').attr('aria-expanded', 'false');
        });
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/views/reorderQuestionnaireQuestions.jsp
<%--
  @author tanmoy.das
  @since 5/2/20
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<spring:message code="label.app.description"/>">
    <meta name="author" content="<spring:message code="label.author.name"/>">

    <title><spring:message code="label.dashboard"/></title>

    <c:url var="dashboardCssUrl" value="/css/dashboard.css"/>
    <link rel="stylesheet" type="text/css" href="${dashboardCssUrl}">
</head>

<c:url var="homepageUrl" value="/"/>
<c:url var="logoutUrl" value="/logout"/>

<body>
<div class="wrapper">
    <!-- Sidebar  -->
    <%@ include file="/WEB-INF/includes/sections/leftSideBar.jsp" %>

    <!-- Page Content  -->
    <div id="content">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fas fa-align-left"></i>
                    <span></span>
                </button>

                <h2 class="mx-3">Reorder Questionnaire Questions</h2>

            </div>
        </nav>

        <div class="tab-content">
            <form:errors path="questionReorderCommand.*" cssClass="alert alert-danger my-3"/>

            <c:url var="questionReorderUrl" value="/questionnaire/update"/>
            <form:form method="post" modelAttribute="questionReorderCommand" action="${questionReorderUrl}">
                <c:set var="questionnaire" value="${questionReorderCommand.questionnaire}"/>

                <form:hidden path="questionnaire.questionOrderJson" cssClass="questionOrderJson"/>
                <div class="my-2">
                    <div class="card mb-2">
                        <div class="card-body">
                            <div class="d-flex flex-column">
                                <h5 class="card-title form-group align-self-start">
                                    <form:input path="questionnaire.label" cssClass="form-control"/>
                                </h5>
                                <h5 class="card-title flex-fill text-muted">
                                    <span>Subject: ${questionnaire.subject.label}</span>
                                </h5>
                            </div>
                            <span>
                            <b><spring:message code="label.chapters"/>:</b>
                            <c:forEach items="${questionnaire.chapterLabels}" var="chapterName">
                                <c:out value="${chapterName}"/>,
                            </c:forEach>
                        </span>
                        </div>


                        <p class="small text-sm-left text-muted ml-4">
                            <spring:message code="dragAndDropToReorder"/>
                        </p>

                    </div>

                    <div class="mb-1 d-flex">
                        <strong class="flex-fill">
                            Questions:
                        </strong>
                        <a href="#"
                           class="text-info"
                           onclick="showReorderModal('#qq${questionnaire.id}', '#qqq${questionnaire.id}')">
                            <u>Reorder Questions</u>
                        </a>
                    </div>

                    <ul class="list-group list-group-flush mb-3" id="qqq${questionnaire.id}">
                        <c:forEach items="${questionnaire.questions}" var="question">
                            <li class="list-group-item border border-secondary mb-3"
                                data-index="${question.id}">
                                <div class="d-flex">
                                    <h5>
                                        <c:out value="${question.code}"/>:
                                        <c:out value="${question.title}"/>
                                    </h5>
                                    <p class="flex-fill ml-3">
                                        [
                                        <c:out value="${question.chapter.label}"/>
                                        ]
                                    </p>
                                </div>
                            </li>
                        </c:forEach>
                    </ul>

                    <div class="modal fade" id="reorderModal" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">
                                        <spring:message code="label.reorderQuestions"/>
                                    </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">

                                    <ul class="list-group list-group-flush card-body pr-0 border-secondary"
                                        id="qq${questionnaire.id}">
                                    </ul>

                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                                    <button type="button" class="btn btn-primary" data-dismiss="modal">
                                        Reorder Questions
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <form:button name="_action_reorder_questions" class="btn btn-primary">
                        <spring:message code="label.saveChanges"/>
                    </form:button>

                </div>
            </form:form>
        </div>
    </div>
</div>


<!-- jQuery Custom Scroller CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js">
</script>

<script>
    $(document).ready(function () {
        $("#sidebar").mCustomScrollbar({
            theme: "minimal"
        });

        $('#sidebarCollapse').on('click', function () {
            $('#sidebar, #content').toggleClass('active');
            $('.collapse.in').toggleClass('in');
            $('a[aria-expanded=true]').attr('aria-expanded', 'false');
        });
    });
</script>

<c:url var="reorderQuestionsWidgetUrl" value="/js/reorderQuestionsWidget.js"/>
<script src="${reorderQuestionsWidgetUrl}"></script>

<script type="text/javascript">
    function showReorderModal(questionListId, updatableListId) {
        let questionDtoList = JSON.parse('${questionReorderCommand.questionDtoList}');
        console.log(questionDtoList);

        $("#reorderModal").reorderQuestionsWidget({
            questionDtoList: questionDtoList,
            modal: 'show',
            target: {
                questionListId: questionListId,
                updatableListId: updatableListId
            }
        });
    }
</script>

</body>
</html>